### PR TITLE
merge pacwall and pacwall-pywal

### PR DESCRIPTION
**Pull request by Quoteme**
in this fork I did the following:
- change screenshot
- added optional pywal compatibility (check if ~/.cache/wal exists, then apply the pywal theme, else leave it)
- removed dependency on feh and use hsetroot instead (one can still use feh by uncommenting `#feh --bg-center --no-fehbg pacwall.png` and commenting out `hsetroot -solid $BACKGROUND -full pacwall.png`
- removed dependency for imagemagic, because filling the desktop-background with the background of the graph and then centering the graph in full size in the middle of the desktop seems to have the same effect
- moved `readme.rst` to `readme.md` because markdown is easier  (read: [https://gist.github.com/dupuy/1855764](https://gist.github.com/dupuy/1855764))
- removed `SCREEN_SIZE`, because using `hsetroot -full` displays the unscaled graph in the center, which worked for me so far

### CODE REVIEW

**Comment by Kharacternyk** [comment]
There is too much merge-conflicts. Could you pull the latest version and redo your changes? For example:

* The code for `pywal` can just be copy pasted, everything should work.
* The code for `hsetroot` should be moved to the `try_set_wallpaper` function.
* Could you add the necessary information about `pywal` to the existing README?
* Could you add your screenshot instead of overwriting the previous one? I suggest a name like `screenshot-pywal.png`.

If it is too much hassle for you, I can do it myself and credit you in a CONTRIBUTORS section of the README (if you allow it).

Mit freundlicen Grüßen:)

**Comment by Quoteme** [comment]
sorry for the hastle 😅
actually, the easiest thing would probably be to just change:
```bash
BACKGROUND=darkslategray
NODE='#dc143c88'
ENODE=darkorange
EDGE='#ffffff44'
```
to:
```bash
# Pick colors.
# test if the wal folder (for pywal) exists
if test -f ~/.cache/wal/colors ; then
	echo "Pywal installed. Using Pywal settings."
	# change `n` in `head -n` to use the n-th terminal color set by pywal
	# you can preview these colors in ~/.cache/wal/colors.json
	BACKGROUND=$( echo "$(cat ~/.cache/wal/colors | head -1 | tail -1)" )
	echo "Background: " $BACKGROUND
	NODE=$( echo "$(cat ~/.cache/wal/colors | head -2 | tail -1)""88" )
	echo "Node: " $NODE
	ENODE=$( echo \""$(cat ~/.cache/wal/colors | head -3 | tail -1)""ff"\" )
	echo "Enode: " $ENODE
	EDGE=$( echo "$(cat ~/.cache/wal/colors | head -8 | tail -1)""44" )
	echo "Edge: " $EDGE
else
	echo "Using default colors."
	BACKGROUND=darkslategray
	NODE='#dc143c88'
	ENODE=darkorange
	EDGE='#ffffff44'
fi
```
for the pywal support.

on second thought, it would probably be better to forget about all this. Your newest version allows for passing the colors for nodes, etc as command line arguments, therefor it would be better for me to just create a helper script that fetches the information from pywal, and then passes these colors to your script.
Sorry for the inconvenience.

**Comment by Kharacternyk** [comment]
I like the idea of built-in pywal support, so that users don't need to extract the colors from `~/.cache/wal/colors` themselves.

Can I add your code for `hsetroot` to `master`? More supported backends is always better.

**Comment by Quoteme** [comment]
yeah sure. `hsetroot -solid $BACKGROUND -full pacwall.png` is what I used to set the wallpaper with `hsetroot`.

сподіваюся, мені вдалося допомогти! (I hope I was abled to help)

**Comment by Kharacternyk** [comment]
Das ist aber interessant, dass viele Menschen aus Deutschland diesem Repo einen Stern gegeben haben. Ich lerne Deutsch schon für einem Jahr, eine schöne Sprache:)

**Comment by Kharacternyk** [comment]
I've implemented pywal integration based on your code (5ffcea2) and have added you to the list of contributors (03c7cc3).

**Pull request closed without merging**
