### PR TITLE
sudo mode implemented

### PR DESCRIPTION
**Pull request by RuijieYu**
`sudo` package in `base-devel` which is assumed to be installed.

### CODE REVIEW

**Comment by Kharacternyk** [comment]
The code is nice, but I've just realised that I don't actually remember why is this needed. Is it for pacman hooks?

**Comment by RuijieYu** [comment]
Yes. I was trying to put it into pacman hooks but the currently supported tools make it very hard to automate the process.

**Comment by Kharacternyk** [comment]
Should it be documented in the help message and the README?

**Comment by Kharacternyk** [comment]
I guess I can merge it now and document the things later.

**Pull request merged**
