### PR TITLE
Make `IMAGE_ONLY` true when screen size specified

### PR DESCRIPTION
**Pull request by ChiDal**
If the user specifies a screen size, he most probably wants to use it for something else. Hence we should not set the wallpaper. Also I made resizing a separate function because it is used in 2 cases - GNOME and screen size specified. This can also make implementing DE mode slightly easier

### CODE REVIEW

**Comment by Kharacternyk** [comment]
Thanks! I'm AFK as of now, so I'll test this later. I'm not sure I understand the motivation though. For example, on Wayland we can't use `xorg-xdpyinfo` and setting the size manually is required.

**Comment by ChiDal** [comment]
Okay, we'll make an exception for wayland

**Comment by ChiDal** [comment]
I'll do it when on pc

**Comment by Kharacternyk** [comment]
I mean, if one sets `SCREEN_SIZE` and doesn't use the image as a wallpaper, then the variable shouldn't be called `SCREEN_SIZE` in the first place, rather `IMAGE_SIZE` or something. I added `-S` just as a workaround on Wayland.

I find the behaviour in this PR a bit confusing. The difference is one keystroke anyway: `pacwall -iS 1920x1200` vs `pacwall -S 1920x1200`.

**Comment by ChiDal** [comment]
The difference is one keystroke anyway - yup you're right

**Pull request closed without merging**
