### PR TITLE
xbps support for void linux

### PR DESCRIPTION
**Pull request by AugustUnderground**
Added a `generate_graph_xbps` function, which generates the graph for packages installed with xbps on void linux.

### CODE REVIEW

**Comment by Kharacternyk** [comment]
Thanks!

**Comment by Kharacternyk** [comment]
@AugustUnderground Why do you color all dependencies using `FNODE`? It's meant to be used for foreign packages. Is it a mistake or do I miss something?

**Comment by AugustUnderground** [comment]
I'm sorry, you are right. That's a typo, It's supposed to be `NODE` instead of `FNODE`. Foreign packages aren't even considered so far.

**Comment by Kharacternyk** [comment]
Could you test whether c193a49 fixes it?

**Comment by AugustUnderground** [comment]
If those 2 lines are removed, the dependencies will be colored with the default node color. That would be `VNODE` as in `-Ncolor=${VNODE}`. Is it supposed to be that way?

**Comment by Kharacternyk** [comment]
I forgot that the default is `VNODE` now. It was still `NODE` just a couple days ago.

We should bring back that two lines and change `FNODE` to `NODE`, you are right.

**Comment by AugustUnderground** [comment]
Yes, that should do it. Thanks, and sorry again for the confusion.

**Pull request merged**
